### ISSUE TITLE
Cursor not dissapearing

### ISSUE THREAD

**Issue by Wynandus** [Skordy/guidehud#2]
So basically, upon opening the menu ingame. And you try exiting out of the menu the cursor doesn't go away and you're not able to do anything in-game. Please fix this is a major bug

**Comment by NotixOfficial** [comment]
That's because you changed the name of resource, just use guidehud or simply go to javascript.
If you want to change name you need to replace this http://guidehud/****** to http://NAMEHERE/*****.

**Comment by Skordy** [comment]
Thanks for the response on this @NotixMLG 

Closing issue.
