### ISSUE TITLE
Using too much RAM message

### ISSUE THREAD

**Issue by Paraxdev** [Skordy/guidehud#3]
![FiveM_GTAProcess_8UtctSYP5G](https://user-images.githubusercontent.com/29353794/72218881-5a74bb00-3540-11ea-88cf-c9209253f3b0.png)
this error occours to everyone no fix found yet

**Comment by iSentrie** [comment]
weird its completely fine for me

**Comment by Skordy** [comment]
Yeah, this resource is super lightweight, and no one else has brought this up. What modifications have you made to it? Try downloading a fresh copy with no modifications and see if the issue persists.

**Comment by Skordy** [comment]
Under testing, I was not able to replicate this issue. It's likely heavy modifications were made. Closing issue.
