### ISSUE TITLE
the help menu wont close it freezes 

### ISSUE THREAD

**Issue by NorthGeorgiaRolplay** [Skordy/guidehud#4]
when you pull up the in game one the mouse doesnt go away and it stays there so in order to get back to playing you have to close fivem and restart your game is there a fix to this or how do you fully close out of the menu

**Comment by Skordy** [comment]
Ensure that the name of the resource folder is "guidehud" without the quotations. Deviating from this name will cause the JavaScript/Lua not to fire properly.

**Comment by NorthGeorgiaRolplay** [comment]
I did that doesn’t work
